### ISSUE TITLE
mc not launching bc of title changer

### ISSUE THREAD

**Issue by Wayturns** [LinsPMStudio/TitleChanger#1]
**Describe the bug**
it crashes the game before it can even launch error code: 1
**To Reproduce**
1.Install title changer
2. put it into mods folder
3. start mc

**Expected behavior**
game launching

**Screenshots**
![image](https://user-images.githubusercontent.com/92233613/206880598-c12dd3ee-306b-4299-8daf-691e95a6bd34.png)
https://mclo.gs/nZ6X9wk

**Desktop (please complete the following information):**
 - Java: [17]
- Minecraft: [1.19.3]

**Comment by lijinhong11** [comment]
You should install LinsAPI first when you are using fabric version. And please check your mod loader is fabric or forge,then download the right version titlechanger.
